### ISSUE TITLE
Content Server - Returning Turtle Content

### ISSUE THREAD

**Issue by calummackervoy** [Multi-User-Domain/mud-jena#1]
Currently the Content Server returns String content, it should return Turtle so that it's machine readable

I guess to start with the front-end needs to know
* that it's returning primaryTextContent
* what it's describing (this specific object, this RDF type)

Open-ended though if you want to return something else, also fine to extend the ontologies

**Comment by calummackervoy** [comment]
@MattTennison I realised this will require the extension of ontologies to replace the properties `primaryTextContent` and `primaryImageContent` with e.g. `sees`, `hears`, `understands`. Probably in a new ontology which will require a new vocabulary LIT and changes the existing ones. It will also break the front-end

Happy to help with or do these consequences, let me know

**Comment by MattTennison** [comment]
> I realised this will require the extension of ontologies to replace the properties primaryTextContent and primaryImageContent with e.g. sees, hears, understands. Probably in a new ontology which will require a new vocabulary LIT and changes the existing ones.

I'll make a start and see how it goes - will reach out for some help if I get stuck 😄 

> It will also break the front-end

Ah - so after we've got a PR ready for this, how should we tackle it? Should we get a equivilant front-end PR ready, that we can merge alongside it, or do you think it'll be pretty easy to fix (and okay to leave broken for a small amount of time)?

**Comment by calummackervoy** [comment]
> Should we get a equivilant front-end PR ready, that we can merge alongside it, or do you think it'll be pretty easy to fix (and okay to leave broken for a small amount of time)?

I think that we should make a concurrent front-end PR? but it's also okay to leave temporarily broken because it will only stop the "clicking on a building and getting a description" feature from working

**Comment by calummackervoy** [comment]
At the moment the vocabs are on my Solid POD which means that only I can push changes

I'll open a new repository for this, but first I'll move the existing repositories into an organisation I think

**Comment by calummackervoy** [comment]
https://github.com/Multi-User-Domain/vocab :tada:
