### ISSUE TITLE
Tomcat: Deploy WAR at root

### ISSUE THREAD

**Issue by calummackervoy** [Multi-User-Domain/mud-jena#42]
In #27 we're adding an endpoint to `localhost:8080/.well-known/...`, WebFinger and other protocols do this as well

Annoyingly in Tomcat I think that this means we need to deploy the app serving these endpoints specially as the root application: https://www.baeldung.com/tomcat-root-application. Annoying mostly because it makes it tricky for someone to run MUD-Jena alongside other apps on Tomcat which want to use the root path

@MattTennison do you know how you'd do this in Docker?

I'm running a Tomcat server in Eclipse and it looks like I can make this change via the settings (https://www.baeldung.com/eclipse-tomcat)

TODO

* [x] Eclipse settings - info in the README or in documentation
* [x] Docker - info in README (if needed)

**Comment by MattTennison** [comment]
For the Docker side of it, it was straightforward - https://github.com/Multi-User-Domain/mud-jena/commit/1209cae9065e6daab26aefa242d2bd566571ac3d
 
This means all built Docker images will serve MUD under the root path. I haven't added anything to the README as it should just work :smile:
